# Generated by Django 5.0.7 on 2024-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
