# Generated by Django 5.0.7 on 2024-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_rename_number_facebook_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='Number',
            field=models.IntegerField(max_length=15),
        ),
    ]
