# Generated by Django 5.0.7 on 2024-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_alter_facebook_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='Number',
            field=models.CharField(max_length=15),
        ),
    ]
